[window]
opacity = 0.95
startup_mode = "Maximized"

[font]
normal = { family = "CodeNewRoman Nerd Font Mono", style = "Regular" }
bold = { family = "CodeNewRoman Nerd Font Mono", style = "Bold" }
italic = { family = "CodeNewRoman Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CodeNewRoman Nerd Font Mono", style = "Bold Italic" }
size = 13.0
